### PR TITLE
Read unknown fields even on empty messages

### LINKED ISSUE #669: Addition of field on empty message breaks backward compatibility
If you define a proto message without any fields but return the message populated with fields in the grpc server,
the decoder won't read the fields and the buffer will get out of sync

To reproduce:

message GrpcTest {
}

// Generate client code

//Update proto

message GrpcTest {
  string test = 1;
}

// Generate server code

### PR DESCRIPTION
**Pull request by jcready**
Fixes #669

### CODE REVIEW

File: packages/plugin/src/message-type-extensions/internal-binary-read.ts [hunk 1]
```diff
@@ -34,21 +34,6 @@ export class InternalBinaryRead implements CustomMethodGenerator {
     make(source: TypescriptFile, descriptor: DescriptorProto): ts.MethodDeclaration[] {
         const methods: ts.MethodDeclaration[] = [];
 
-        // if the message has no fields, we produce a much shorter body:
```
Comment (timostamm) [inline packages/plugin/src/message-type-extensions/internal-binary-read.ts:37]: Messages with zero fields should be rare. This probably wasn't very useful.

**Review by timostamm — APPROVED** [review]
Thanks for the fix!
